spring.application.name=rate-limiter-service
maxTokens=4
windowSeconds=60
maxTokensForTokenBucket=4.0
leakyBucketSize=4
outflowRate=2
slidingWindowMaxRequests=4

spring.redis.host=localhost
spring.redis.port=6379

circuit.breaker.failure.threshold=5
circuit.breaker.timeout.seconds=30
rule.engine.storage.file=rules.json