spring.application.name=rate-limiter-service
maxTokens=4
windowSeconds=60
maxTokensForTokenBucket=4.0
leakyBucketSize=4
outflowRate=2
slidingWindowMaxRequests=4

spring.redis.host=localhost
spring.redis.port=6379

circuit.breaker.failure.threshold=5
circuit.breaker.timeout.seconds=30
rule.engine.storage.file=rules.json

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

logging.level.root=INFO
logging.level.com.ratelimiter=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n